/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.joda.time.DateTime;

/**
 * LessonItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T15:21:51.713+08:00")
public class LessonItem {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("thumbnail")
  private String thumbnail = null;

  @SerializedName("difficulty")
  private Long difficulty = null;

  @SerializedName("viewCount")
  private Long viewCount = null;

  @SerializedName("likeCount")
  private Long likeCount = null;

  @SerializedName("ageRange")
  private AgeRange ageRange = null;

  @SerializedName("category")
  private LessonCategory category = null;

  @SerializedName("type")
  private LessonType type = null;

  @SerializedName("stages")
  private List<StageItem> stages = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("createTime")
  private DateTime createTime = null;

  public LessonItem id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public LessonItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "lesson1", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LessonItem thumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @ApiModelProperty(example = "http://test/test.png", value = "")
  public String getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }

  public LessonItem difficulty(Long difficulty) {
    this.difficulty = difficulty;
    return this;
  }

   /**
   * Get difficulty
   * @return difficulty
  **/
  @ApiModelProperty(example = "5", value = "")
  public Long getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(Long difficulty) {
    this.difficulty = difficulty;
  }

  public LessonItem viewCount(Long viewCount) {
    this.viewCount = viewCount;
    return this;
  }

   /**
   * Get viewCount
   * @return viewCount
  **/
  @ApiModelProperty(example = "123", value = "")
  public Long getViewCount() {
    return viewCount;
  }

  public void setViewCount(Long viewCount) {
    this.viewCount = viewCount;
  }

  public LessonItem likeCount(Long likeCount) {
    this.likeCount = likeCount;
    return this;
  }

   /**
   * Get likeCount
   * @return likeCount
  **/
  @ApiModelProperty(example = "123", value = "")
  public Long getLikeCount() {
    return likeCount;
  }

  public void setLikeCount(Long likeCount) {
    this.likeCount = likeCount;
  }

  public LessonItem ageRange(AgeRange ageRange) {
    this.ageRange = ageRange;
    return this;
  }

   /**
   * Get ageRange
   * @return ageRange
  **/
  @ApiModelProperty(value = "")
  public AgeRange getAgeRange() {
    return ageRange;
  }

  public void setAgeRange(AgeRange ageRange) {
    this.ageRange = ageRange;
  }

  public LessonItem category(LessonCategory category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public LessonCategory getCategory() {
    return category;
  }

  public void setCategory(LessonCategory category) {
    this.category = category;
  }

  public LessonItem type(LessonType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public LessonType getType() {
    return type;
  }

  public void setType(LessonType type) {
    this.type = type;
  }

  public LessonItem stages(List<StageItem> stages) {
    this.stages = stages;
    return this;
  }

  public LessonItem addStagesItem(StageItem stagesItem) {
    if (this.stages == null) {
      this.stages = new ArrayList<StageItem>();
    }
    this.stages.add(stagesItem);
    return this;
  }

   /**
   * Get stages
   * @return stages
  **/
  @ApiModelProperty(value = "")
  public List<StageItem> getStages() {
    return stages;
  }

  public void setStages(List<StageItem> stages) {
    this.stages = stages;
  }

  public LessonItem creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @ApiModelProperty(example = "wangtt", value = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public LessonItem createTime(DateTime createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @ApiModelProperty(example = "2016-08-29T09:12:33.001+0000", value = "")
  public DateTime getCreateTime() {
    return createTime;
  }

  public void setCreateTime(DateTime createTime) {
    this.createTime = createTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LessonItem lessonItem = (LessonItem) o;
    return Objects.equals(this.id, lessonItem.id) &&
        Objects.equals(this.name, lessonItem.name) &&
        Objects.equals(this.thumbnail, lessonItem.thumbnail) &&
        Objects.equals(this.difficulty, lessonItem.difficulty) &&
        Objects.equals(this.viewCount, lessonItem.viewCount) &&
        Objects.equals(this.likeCount, lessonItem.likeCount) &&
        Objects.equals(this.ageRange, lessonItem.ageRange) &&
        Objects.equals(this.category, lessonItem.category) &&
        Objects.equals(this.type, lessonItem.type) &&
        Objects.equals(this.stages, lessonItem.stages) &&
        Objects.equals(this.creator, lessonItem.creator) &&
        Objects.equals(this.createTime, lessonItem.createTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, thumbnail, difficulty, viewCount, likeCount, ageRange, category, type, stages, creator, createTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LessonItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
    sb.append("    viewCount: ").append(toIndentedString(viewCount)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    ageRange: ").append(toIndentedString(ageRange)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

