/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LevelNavigation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T00:47:33.626+08:00")
public class LevelNavigation {
  @SerializedName("previousLevelURL")
  private String previousLevelURL = null;

  @SerializedName("currentLevelURL")
  private String currentLevelURL = null;

  @SerializedName("nextLevelURL")
  private String nextLevelURL = null;

  public LevelNavigation previousLevelURL(String previousLevelURL) {
    this.previousLevelURL = previousLevelURL;
    return this;
  }

   /**
   * Get previousLevelURL
   * @return previousLevelURL
  **/
  @ApiModelProperty(value = "")
  public String getPreviousLevelURL() {
    return previousLevelURL;
  }

  public void setPreviousLevelURL(String previousLevelURL) {
    this.previousLevelURL = previousLevelURL;
  }

  public LevelNavigation currentLevelURL(String currentLevelURL) {
    this.currentLevelURL = currentLevelURL;
    return this;
  }

   /**
   * Get currentLevelURL
   * @return currentLevelURL
  **/
  @ApiModelProperty(value = "")
  public String getCurrentLevelURL() {
    return currentLevelURL;
  }

  public void setCurrentLevelURL(String currentLevelURL) {
    this.currentLevelURL = currentLevelURL;
  }

  public LevelNavigation nextLevelURL(String nextLevelURL) {
    this.nextLevelURL = nextLevelURL;
    return this;
  }

   /**
   * Get nextLevelURL
   * @return nextLevelURL
  **/
  @ApiModelProperty(value = "")
  public String getNextLevelURL() {
    return nextLevelURL;
  }

  public void setNextLevelURL(String nextLevelURL) {
    this.nextLevelURL = nextLevelURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelNavigation levelNavigation = (LevelNavigation) o;
    return Objects.equals(this.previousLevelURL, levelNavigation.previousLevelURL) &&
        Objects.equals(this.currentLevelURL, levelNavigation.currentLevelURL) &&
        Objects.equals(this.nextLevelURL, levelNavigation.nextLevelURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previousLevelURL, currentLevelURL, nextLevelURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelNavigation {\n");
    
    sb.append("    previousLevelURL: ").append(toIndentedString(previousLevelURL)).append("\n");
    sb.append("    currentLevelURL: ").append(toIndentedString(currentLevelURL)).append("\n");
    sb.append("    nextLevelURL: ").append(toIndentedString(nextLevelURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

