/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * LevelVideo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T00:47:33.626+08:00")
public class LevelVideo {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("level_name")
  private String levelName = null;

  @SerializedName("level_video_src")
  private String levelVideoSrc = null;

  public LevelVideo id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public LevelVideo levelName(String levelName) {
    this.levelName = levelName;
    return this;
  }

   /**
   * Get levelName
   * @return levelName
  **/
  @ApiModelProperty(value = "")
  public String getLevelName() {
    return levelName;
  }

  public void setLevelName(String levelName) {
    this.levelName = levelName;
  }

  public LevelVideo levelVideoSrc(String levelVideoSrc) {
    this.levelVideoSrc = levelVideoSrc;
    return this;
  }

   /**
   * Get levelVideoSrc
   * @return levelVideoSrc
  **/
  @ApiModelProperty(value = "")
  public String getLevelVideoSrc() {
    return levelVideoSrc;
  }

  public void setLevelVideoSrc(String levelVideoSrc) {
    this.levelVideoSrc = levelVideoSrc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelVideo levelVideo = (LevelVideo) o;
    return Objects.equals(this.id, levelVideo.id) &&
        Objects.equals(this.levelName, levelVideo.levelName) &&
        Objects.equals(this.levelVideoSrc, levelVideo.levelVideoSrc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, levelName, levelVideoSrc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelVideo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    levelName: ").append(toIndentedString(levelName)).append("\n");
    sb.append("    levelVideoSrc: ").append(toIndentedString(levelVideoSrc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

