/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * LevelRobertaProperty
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T15:21:51.713+08:00")
public class LevelRobertaProperty {
  @SerializedName("level_id")
  private UUID levelId = null;

  @SerializedName("level_type")
  private LevelRobertaType levelType = null;

  @SerializedName("level_toolbox")
  private String levelToolbox = null;

  public LevelRobertaProperty levelId(UUID levelId) {
    this.levelId = levelId;
    return this;
  }

   /**
   * Get levelId
   * @return levelId
  **/
  @ApiModelProperty(value = "")
  public UUID getLevelId() {
    return levelId;
  }

  public void setLevelId(UUID levelId) {
    this.levelId = levelId;
  }

  public LevelRobertaProperty levelType(LevelRobertaType levelType) {
    this.levelType = levelType;
    return this;
  }

   /**
   * Get levelType
   * @return levelType
  **/
  @ApiModelProperty(value = "")
  public LevelRobertaType getLevelType() {
    return levelType;
  }

  public void setLevelType(LevelRobertaType levelType) {
    this.levelType = levelType;
  }

  public LevelRobertaProperty levelToolbox(String levelToolbox) {
    this.levelToolbox = levelToolbox;
    return this;
  }

   /**
   * Get levelToolbox
   * @return levelToolbox
  **/
  @ApiModelProperty(value = "")
  public String getLevelToolbox() {
    return levelToolbox;
  }

  public void setLevelToolbox(String levelToolbox) {
    this.levelToolbox = levelToolbox;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelRobertaProperty levelRobertaProperty = (LevelRobertaProperty) o;
    return Objects.equals(this.levelId, levelRobertaProperty.levelId) &&
        Objects.equals(this.levelType, levelRobertaProperty.levelType) &&
        Objects.equals(this.levelToolbox, levelRobertaProperty.levelToolbox);
  }

  @Override
  public int hashCode() {
    return Objects.hash(levelId, levelType, levelToolbox);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelRobertaProperty {\n");
    
    sb.append("    levelId: ").append(toIndentedString(levelId)).append("\n");
    sb.append("    levelType: ").append(toIndentedString(levelType)).append("\n");
    sb.append("    levelToolbox: ").append(toIndentedString(levelToolbox)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

