/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LevelRobertaType
 */
@JsonAdapter(LevelRobertaType.Adapter.class)
public enum LevelRobertaType {
  
  INSTRUCTION("instruction"),
  
  PROGRAM("program");

  private String value;

  LevelRobertaType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LevelRobertaType fromValue(String text) {
    for (LevelRobertaType b : LevelRobertaType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LevelRobertaType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LevelRobertaType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LevelRobertaType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LevelRobertaType.fromValue(String.valueOf(value));
    }
  }
}

