/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * LevelCodeCamp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T00:47:33.626+08:00")
public class LevelCodeCamp {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("level_name")
  private String levelName = null;

  @SerializedName("level_title")
  private String levelTitle = null;

  @SerializedName("level_description")
  private String levelDescription = null;

  @SerializedName("level_tests")
  private String levelTests = null;

  @SerializedName("level_challenge_seed")
  private String levelChallengeSeed = null;

  public LevelCodeCamp id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public LevelCodeCamp levelName(String levelName) {
    this.levelName = levelName;
    return this;
  }

   /**
   * Get levelName
   * @return levelName
  **/
  @ApiModelProperty(value = "")
  public String getLevelName() {
    return levelName;
  }

  public void setLevelName(String levelName) {
    this.levelName = levelName;
  }

  public LevelCodeCamp levelTitle(String levelTitle) {
    this.levelTitle = levelTitle;
    return this;
  }

   /**
   * Get levelTitle
   * @return levelTitle
  **/
  @ApiModelProperty(value = "")
  public String getLevelTitle() {
    return levelTitle;
  }

  public void setLevelTitle(String levelTitle) {
    this.levelTitle = levelTitle;
  }

  public LevelCodeCamp levelDescription(String levelDescription) {
    this.levelDescription = levelDescription;
    return this;
  }

   /**
   * Get levelDescription
   * @return levelDescription
  **/
  @ApiModelProperty(value = "")
  public String getLevelDescription() {
    return levelDescription;
  }

  public void setLevelDescription(String levelDescription) {
    this.levelDescription = levelDescription;
  }

  public LevelCodeCamp levelTests(String levelTests) {
    this.levelTests = levelTests;
    return this;
  }

   /**
   * Get levelTests
   * @return levelTests
  **/
  @ApiModelProperty(value = "")
  public String getLevelTests() {
    return levelTests;
  }

  public void setLevelTests(String levelTests) {
    this.levelTests = levelTests;
  }

  public LevelCodeCamp levelChallengeSeed(String levelChallengeSeed) {
    this.levelChallengeSeed = levelChallengeSeed;
    return this;
  }

   /**
   * Get levelChallengeSeed
   * @return levelChallengeSeed
  **/
  @ApiModelProperty(value = "")
  public String getLevelChallengeSeed() {
    return levelChallengeSeed;
  }

  public void setLevelChallengeSeed(String levelChallengeSeed) {
    this.levelChallengeSeed = levelChallengeSeed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelCodeCamp levelCodeCamp = (LevelCodeCamp) o;
    return Objects.equals(this.id, levelCodeCamp.id) &&
        Objects.equals(this.levelName, levelCodeCamp.levelName) &&
        Objects.equals(this.levelTitle, levelCodeCamp.levelTitle) &&
        Objects.equals(this.levelDescription, levelCodeCamp.levelDescription) &&
        Objects.equals(this.levelTests, levelCodeCamp.levelTests) &&
        Objects.equals(this.levelChallengeSeed, levelCodeCamp.levelChallengeSeed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, levelName, levelTitle, levelDescription, levelTests, levelChallengeSeed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelCodeCamp {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    levelName: ").append(toIndentedString(levelName)).append("\n");
    sb.append("    levelTitle: ").append(toIndentedString(levelTitle)).append("\n");
    sb.append("    levelDescription: ").append(toIndentedString(levelDescription)).append("\n");
    sb.append("    levelTests: ").append(toIndentedString(levelTests)).append("\n");
    sb.append("    levelChallengeSeed: ").append(toIndentedString(levelChallengeSeed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

