/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * LevelStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-05T15:21:51.713+08:00")
public class LevelStatus {
  @SerializedName("levelID")
  private UUID levelID = null;

  @SerializedName("scriptID")
  private UUID scriptID = null;

  @SerializedName("statusType")
  private Integer statusType = null;

  public LevelStatus levelID(UUID levelID) {
    this.levelID = levelID;
    return this;
  }

   /**
   * Get levelID
   * @return levelID
  **/
  @ApiModelProperty(value = "")
  public UUID getLevelID() {
    return levelID;
  }

  public void setLevelID(UUID levelID) {
    this.levelID = levelID;
  }

  public LevelStatus scriptID(UUID scriptID) {
    this.scriptID = scriptID;
    return this;
  }

   /**
   * Get scriptID
   * @return scriptID
  **/
  @ApiModelProperty(value = "")
  public UUID getScriptID() {
    return scriptID;
  }

  public void setScriptID(UUID scriptID) {
    this.scriptID = scriptID;
  }

  public LevelStatus statusType(Integer statusType) {
    this.statusType = statusType;
    return this;
  }

   /**
   * Get statusType
   * @return statusType
  **/
  @ApiModelProperty(value = "")
  public Integer getStatusType() {
    return statusType;
  }

  public void setStatusType(Integer statusType) {
    this.statusType = statusType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelStatus levelStatus = (LevelStatus) o;
    return Objects.equals(this.levelID, levelStatus.levelID) &&
        Objects.equals(this.scriptID, levelStatus.scriptID) &&
        Objects.equals(this.statusType, levelStatus.statusType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(levelID, scriptID, statusType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelStatus {\n");
    
    sb.append("    levelID: ").append(toIndentedString(levelID)).append("\n");
    sb.append("    scriptID: ").append(toIndentedString(scriptID)).append("\n");
    sb.append("    statusType: ").append(toIndentedString(statusType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

