/*
 * stemgarden api
 * stemgarden api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.stemweb.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * StageStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T00:47:33.626+08:00")
public class StageStatus {
  @SerializedName("stageID")
  private UUID stageID = null;

  @SerializedName("subStageList")
  private List<StageStatus> subStageList = null;

  @SerializedName("levelStatusList")
  private List<LevelStatus> levelStatusList = null;

  @SerializedName("percentage")
  private Double percentage = null;

  public StageStatus stageID(UUID stageID) {
    this.stageID = stageID;
    return this;
  }

   /**
   * Get stageID
   * @return stageID
  **/
  @ApiModelProperty(value = "")
  public UUID getStageID() {
    return stageID;
  }

  public void setStageID(UUID stageID) {
    this.stageID = stageID;
  }

  public StageStatus subStageList(List<StageStatus> subStageList) {
    this.subStageList = subStageList;
    return this;
  }

  public StageStatus addSubStageListItem(StageStatus subStageListItem) {
    if (this.subStageList == null) {
      this.subStageList = new ArrayList<StageStatus>();
    }
    this.subStageList.add(subStageListItem);
    return this;
  }

   /**
   * Get subStageList
   * @return subStageList
  **/
  @ApiModelProperty(value = "")
  public List<StageStatus> getSubStageList() {
    return subStageList;
  }

  public void setSubStageList(List<StageStatus> subStageList) {
    this.subStageList = subStageList;
  }

  public StageStatus levelStatusList(List<LevelStatus> levelStatusList) {
    this.levelStatusList = levelStatusList;
    return this;
  }

  public StageStatus addLevelStatusListItem(LevelStatus levelStatusListItem) {
    if (this.levelStatusList == null) {
      this.levelStatusList = new ArrayList<LevelStatus>();
    }
    this.levelStatusList.add(levelStatusListItem);
    return this;
  }

   /**
   * Get levelStatusList
   * @return levelStatusList
  **/
  @ApiModelProperty(value = "")
  public List<LevelStatus> getLevelStatusList() {
    return levelStatusList;
  }

  public void setLevelStatusList(List<LevelStatus> levelStatusList) {
    this.levelStatusList = levelStatusList;
  }

  public StageStatus percentage(Double percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * @return percentage
  **/
  @ApiModelProperty(value = "")
  public Double getPercentage() {
    return percentage;
  }

  public void setPercentage(Double percentage) {
    this.percentage = percentage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StageStatus stageStatus = (StageStatus) o;
    return Objects.equals(this.stageID, stageStatus.stageID) &&
        Objects.equals(this.subStageList, stageStatus.subStageList) &&
        Objects.equals(this.levelStatusList, stageStatus.levelStatusList) &&
        Objects.equals(this.percentage, stageStatus.percentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stageID, subStageList, levelStatusList, percentage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StageStatus {\n");
    
    sb.append("    stageID: ").append(toIndentedString(stageID)).append("\n");
    sb.append("    subStageList: ").append(toIndentedString(subStageList)).append("\n");
    sb.append("    levelStatusList: ").append(toIndentedString(levelStatusList)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

