apiVersion: v1
kind: Service
metadata:
  labels:
    app: robertalabapp
    component: robertalab
  name: robertalab
spec:
  ports:
  - port: 80
  selector:
    app: robertalabapp
    component: robertalab
  type: LoadBalancer
  loadBalancerIP: 40.125.207.157
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: robertalab
spec:
  template:
    metadata:
      labels:
        app: robertalabapp
        component: robertalab
    spec:
      containers:
      - name: robertalab
        image: csdiregistry.azurecr.io/stem/robertalab:<robertalab_version>
        imagePullPolicy: Always
        ports:
        - containerPort: 1999
      imagePullSecrets:
      - name: csdiregsecret
