apiVersion: v1
kind: Service
metadata:
  labels:
    app: robertalabapp
    component: robertalab
  name: robertalab
spec:
  ports:
  - port: 1999
    targetPort: 1999
  selector:
    app: robertalabapp
    component: robertalab